### ISSUE TITLE
IPython 没有安装，请在当前版本下安装.

### ISSUE THREAD

**Issue by samualle** [w0lker/emacs.d#1]
你好，我在切换 python-mode 的时候，出现了这样的提示：“IPython 没有安装，请在当前版本下安装.”，但是，我的系统中已经安装有IPython了。能请教一下原因吗？

**Comment by w0lker** [comment]
你是否使用的pyenv的虚拟环境？

**Comment by w0lker** [comment]
@wangshuaibing 你是否使用的**pyenv**虚拟环境？我目前的版本必须要有pyenv环境支持的，这个版本是我重新实现的python开发环境可能还不是很完善，可以使用版本[1.1.11](https://github.com/w0lker/emacs.d/tree/1.1.11)，这个版本使用的anaconda-mode实现。

**Comment by samualle** [comment]
@w0lker 谢谢了，我再琢磨琢磨。可能和 pyenv 有关吧，我使用的是 virtualenv，没有使用 pyenv。

**Comment by w0lker** [comment]
@wangshuaibing 不谢，没事的，基本坚持使用2个月就会熟练了。
